name: root-framework
base: core20
summary: Analyzing petabytes of data, scientifically.
description: |
  https://root.cern

  This snap is intended to provide an easy-to-install package of the ROOT framework for home users and students.
  This package is ideal for users who are looking for an easy installation process that is consistent across systems without the need for integration with other frameworks, IDE's, or external packages.
  For these use-cases, you may want to take a look at other available builds of ROOT at https://root.cern/install/

  Snaps are container packages for easy application deployment, designed to be consistent and reliable across different host distributions.
  They additionally impose some strong sandboxing for security. One caveat of this sandboxing is that this package can only read/write to your `$HOME` directory, or via specific network protocols.
  It is highly advised that you place all your data files in your `$HOME` directory to be accessible.

  Because snaps are containers and don't affect the host system, using PyROOT with `import ROOT` will not work in a system Python shell.
  Users are encouraged to use the command `pyroot` to access the containers' Python shell, where `import ROOT` would become available.
  Scripts can be passed to `pyroot` to be executed in PyROOTs context, E.G, `pyroot ./myScript.py`, or put in the scripts shebang. E.G `#!/snap/bin/pyroot`

  JupyROOT can be accessed by running `root --notebook`.

  For user convenience, application entries for ROOT and PyROOT will be placed into the systems start menu by default.

confinement: strict
license: LGPL-2.1+ AND GPL-3.0
adopt-info: root
compression: lzo
assumes:
  - snap-env
  - command-chain

parts:
  root:
    plugin: cmake
    source: https://github.com/root-project/root.git
    source-commit: e8464159f683e1f2843bce86d6aeac5152075451 #v6.26.6
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=17
    build-packages:
      - libx11-dev
      - libxpm-dev
      - libxft-dev
      - libxext-dev
      - libpython3-dev
      - libssl-dev
      - libpcre++-dev
      - liblzma-dev
      - libzstd-dev
      - libxxhash-dev
      - liblz4-dev
      - libgif-dev
      - libtiff-dev
      - libjpeg-dev
      - libafterimage-dev
      - libgsl-dev
      - libglu1-mesa-dev
      - libxml2-dev
      - libsqlite3-dev
      - libfftw3-dev
      - libcfitsio-dev
      - libtbb-dev
      - libblas-dev
      - libftgl-dev
      - libpythia8-dev
      - libglew-dev
      - davix-dev
      - libgl2ps-dev
      - gfortran
    stage-packages:
      - cmake
      - g++
      - libafterimage0
      - libasn1-8-heimdal
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcfitsio8
      - libcurl3-gnutls
      - libdatrie1
      - libfftw3-double3
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libftgl2
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgsl23
      - libgslcblas0
      - libgssapi3-heimdal
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu66
      - libjbig0
      - libjpeg-turbo8
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libpython3.8
      - libroken18-heimdal
      - librsvg2-2
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libtbb2
      - libthai0
      - libtiff5
      - libwebp6
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxml2
      - libxpm4
      - libxrender1
      - libxxhash0
      - libblas3
      - libstdc++-9-dev
      - libc6-dev
      - libdavix0v5
      - libgl2ps1.4
      - libglew2.1
      - libpythia8v5
      - python3-dev
      - curl
      - make
      - gfortran
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
    override-pull: |
      snapcraftctl pull
      minor_version=$(git describe --tags --abbrev=0 | grep -Eo "[0-9]*-[0-9]*-[0-9]*" | cut -d "-" -f 2)
      patch_version=$(git describe --tags --abbrev=0 | grep -Eo "[0-9]*-[0-9]*-[0-9]*" | cut -d "-" -f 3)
      if [ $(( 10#$minor_version % 2 )) -eq 0 ] && [ $(( 10#$patch_version % 2 )) -eq 0 ]
      then
        snapcraftctl set-grade stable
        snapcraftctl set-version "$(git describe --tags --abbrev=0)"
      else
        snapcraftctl set-grade devel
        snapcraftctl set-version "$(git rev-parse --short HEAD).$(date -u +%d-%m-%y)"
      fi
      patch -i $SNAPCRAFT_PROJECT_DIR/snap/local/patches/ROOT/ACliC.patch -p 1
      patch -i $SNAPCRAFT_PROJECT_DIR/snap/local/patches/ROOT/cli_tools_pyenv_fix.patch -p 1
    override-build: |
      snapcraftctl build

      # Correct CMake containing references to the build environment
      for file in $(grep "/root/parts/root/install\|/root/parts/root/build\|/root/stage" ${SNAPCRAFT_PART_INSTALL}/usr/local/cmake -r -I | cut -d ":" -f 1 | uniq); do
        sed -i 's!/root/parts/root/install!/snap/root-framework/current!g' $file
        sed -i 's!/root/parts/root/build!/snap/root-framework/current!g' $file
        sed -i 's!/root/stage!/snap/root-framework/current!g' $file
      done

      # Prevent use of -isystem in CMake configuration because it breaks "#include_next"
      for file in $(grep "isystem" ${SNAPCRAFT_PART_INSTALL}/usr/local/cmake -r -I | cut -d ":" -f 1 | uniq); do
        sed -i 's!\-isystem!\-I!g' $file
      done
    override-prime: |
      snapcraftctl prime
      cd $SNAPCRAFT_PRIME/usr/bin
      if [[ ! -f c++ ]] ; then ln -s g++ c++ ; fi # ACLiC
      if [[ ! -f cc ]] ; then ln -s gcc cc ; fi # E.G MadGraph
    after:
      [python-modules]


  extras:
    plugin: dump
    source: extras/

  python-modules:
    plugin: python
    source: extras/ # Defined above, will effectively no-op as it should deduplicate with extras part
    requirements: ["${SNAPCRAFT_PROJECT_DIR}/snap/local/requirements.txt"]
    stage-packages:
      - libgomp1
      - libtbb2
    override-build: |
      snapcraftctl build
      rm $SNAPCRAFT_PART_INSTALL/lib64
      patch -d $SNAPCRAFT_PART_INSTALL -i $SNAPCRAFT_PROJECT_DIR/snap/local/patches/notebook/checkpoints.patch -p0
      patch -d $SNAPCRAFT_PART_INSTALL -i $SNAPCRAFT_PROJECT_DIR/snap/local/patches/notebook/atomic_saves.patch -p0
      patch -d $SNAPCRAFT_PART_INSTALL -i $SNAPCRAFT_PROJECT_DIR/snap/local/patches/notebook/disable_file_redirect.patch -p0

environment:
  PATH: ${SNAP}/usr/local/bin:${PATH}
  PIP_TARGET: ${SNAP_USER_COMMON}/.pip
  PYTHONPATH: ${SNAP}/usr/local/lib:${SNAP_USER_COMMON}/.pip
  LD_LIBRARY_PATH: ${SNAP}/usr/local/lib
  CLING_STANDARD_PCH: none
  old_rootsys: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  DYLD_LIBRARY_PATH: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  SHLIB_PATH: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  LIBPATH: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  MANPATH: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  CMAKE_PREFIX_PATH: ${SNAP}
  JUPYTER_PATH: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  JUPYTER_CONFIG_DIR: ${ThisVarIntentionallyDoesNotExistRabbitCake}
  ROOTSYS: ${SNAP}/usr/local
  DISABLE_WAYLAND: 1
  MATPLOTLIBRC: ${SNAP}/etc/matplotlibrc
  XAUTHORITY: ${SNAP_REAL_HOME}/.Xauthority
  LANG: C.UTF-8

layout:
  /usr/share/libdrm:
    symlink: $SNAP/usr/share/libdrm
  /usr/include:
    bind: $SNAP/usr/include
  /usr/share/matplotlib:
    symlink: $SNAP/usr/share/matplotlib
  /usr/lib/x86_64-linux-gnu/libc_nonshared.a: # ACLiC
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libc_nonshared.a

plugs:
  home:
  network:
  opengl:
  x11:
  desktop:
  desktop-legacy:
  removable-media:
  shared-memory:
    private: true

apps:
  root-framework:
    command: usr/local/bin/root
    command-chain:
      - bin/setup-sandbox.sh
  pyroot:
    command: bin/pyroot.sh
    command-chain:
     - bin/setup-sandbox.sh
  genreflex:
    command: usr/local/bin/genreflex
    command-chain:
     - bin/setup-sandbox.sh
  hadd:
    command: usr/local/bin/hadd
    command-chain:
     - bin/setup-sandbox.sh
  hist2workspace:
    command: usr/local/bin/hist2workspace
    command-chain:
     - bin/setup-sandbox.sh
  prepareHistFactory:
    command: usr/local/bin/prepareHistFactory
    command-chain:
     - bin/setup-sandbox.sh
  proofserv:
    command: usr/local/bin/proofserv
    command-chain:
     - bin/setup-sandbox.sh
  rmkdepend:
    command: usr/local/bin/rmkdepend
    command-chain:
     - bin/setup-sandbox.sh
  root-config:
    command: usr/local/bin/root-config
    command-chain:
     - bin/setup-sandbox.sh
  rootbrowse:
    command: usr/local/bin/rootbrowse
    command-chain:
     - bin/setup-sandbox.sh
  rootcint:
    command: usr/local/bin/rootcint
    command-chain:
     - bin/setup-sandbox.sh
  rootcling:
    command: usr/local/bin/rootcling
    command-chain:
     - bin/setup-sandbox.sh
  rootcp:
    command: usr/local/bin/rootcp
    command-chain:
     - bin/setup-sandbox.sh
  rootdrawtree:
    command: usr/local/bin/rootdrawtree
    command-chain:
     - bin/setup-sandbox.sh
  rooteventselector:
    command: usr/local/bin/rooteventselector
    command-chain:
     - bin/setup-sandbox.sh
  rootls:
    command: usr/local/bin/rootls
    command-chain:
     - bin/setup-sandbox.sh
  rootmkdir:
    command: usr/local/bin/rootmkdir
    command-chain:
     - bin/setup-sandbox.sh
  rootmv:
    command: usr/local/bin/rootmv
    command-chain:
     - bin/setup-sandbox.sh
  rootprint:
    command: usr/local/bin/rootprint
    command-chain:
     - bin/setup-sandbox.sh
  rootrm:
    command: usr/local/bin/rootrm
    command-chain:
     - bin/setup-sandbox.sh
  roots:
    command: usr/local/bin/roots
    command-chain:
     - bin/setup-sandbox.sh
  rootslimtree:
    command: usr/local/bin/rootslimtree
    command-chain:
     - bin/setup-sandbox.sh
  xpdtest:
    command: usr/local/bin/xpdtest
    command-chain:
     - bin/setup-sandbox.sh
  root-exe:
    command: usr/local/bin/root.exe
    command-chain:
     - bin/setup-sandbox.sh
  rootn-exe:
    command: usr/local/bin/rootn.exe
    command-chain:
     - bin/setup-sandbox.sh
  rootnb-exe:
    command: usr/local/bin/rootnb.exe
    command-chain:
     - bin/setup-sandbox.sh
  roots-exe:
    command: usr/local/bin/roots.exe
    command-chain:
     - bin/setup-sandbox.sh
  proofserv-exe:
    command: usr/local/bin/proofserv.exe
    command-chain:
     - bin/setup-sandbox.sh
  cmake:
    command: usr/bin/cmake
    command-chain:
      - bin/setup-sandbox.sh
  make:
    command: usr/bin/make
    command-chain:
      - bin/setup-sandbox.sh
  run:
    command: bin/run.sh
    command-chain:
      - bin/setup-sandbox.sh
  pip:
    command: bin/pip
    command-chain:
      - bin/setup-sandbox.sh
