name: root-framework
base: core22
summary: Analyzing petabytes of data, scientifically.
description: |
  https://root.cern

  This snap is intended to provide an easy-to-install package of the ROOT framework for home users and students.
  This package is ideal for users who are looking for an easy installation process that is consistent across systems without the need for integration with other frameworks, IDE's, or external packages.
  For these use-cases, you may want to take a look at other available builds of ROOT at https://root.cern/install/

  Snaps are container packages for easy application deployment, designed to be consistent and reliable across different host distributions.
  They additionally impose some strong sandboxing for security. One caveat of this sandboxing is that this package can only read/write to your `$HOME` directory, or via specific network protocols.
  It is highly advised that you place all your data files in your `$HOME` directory to be accessible.

  Because snaps are containers and don't affect the host system, using PyROOT with `import ROOT` will not work in a system Python shell.
  Users are encouraged to use the command `pyroot` to access the containers' Python shell, where `import ROOT` would become available.
  Scripts can be passed to `pyroot` to be executed in PyROOTs context, E.G, `pyroot ./myScript.py`, or put in the scripts shebang. E.G `#!/snap/bin/pyroot`

  JupyROOT can be accessed by running `root --notebook`.

  For user convenience, application entries for ROOT and PyROOT will be placed into the systems start menu by default.

confinement: strict
license: LGPL-2.1+ AND GPL-3.0
adopt-info: root
compression: lzo
assumes:
  - snap-env
  - command-chain

parts:
  root:
    plugin: cmake
    source: https://github.com/root-project/root.git
    source-commit: 40b4fb78539edc2729af62cdd6c5f1924d6b5853 # 6.28.06
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=17
      - -Dxrootd=OFF
      - -Dbuiltin_xrootd=OFF
    build-packages:
      - build-essential
      # headers
      - libxpm-dev
      - libxft-dev
      - libxext-dev
      - libssl-dev
      - gfortran
      - libpcre++-dev
      - xlibmesa-glu-dev
      - libglew-dev
      - libfftw3-dev
      - libcfitsio-dev
      - libgraphviz-dev
      - libpython3-dev
      - libxml2-dev
      - libkrb5-dev
      # Toolchain
      - g++
      - gfortran
      - cmake
    stage-packages:
      # Headers
      - libstdc++-11-dev
      - libpython3-dev
      - libxft-dev
      - libxpm-dev
      - libxpm4
      - libxext-dev
      - libssl-dev
      - libpcre++-dev
      - xlibmesa-glu-dev
      - libglew-dev
      - libfftw3-dev
      - libcfitsio-dev
      - libgraphviz-dev
      - libavahi-compat-libdnssd-dev
      - libldap2-dev
      - libpython3-dev
      - libxml2-dev
      - libkrb5-dev
      - libgsl0-dev
      # Toolchain
      - gfortran
      - g++
      - cmake
      - make
      # Libraries
      - x11-utils
      - libglu1-mesa
      # Utilities
      - curl
      - wget
    override-pull: |
      craftctl default
      minor_version=$(git describe --tags --abbrev=0 | grep -Eo "[0-9]*-[0-9]*-[0-9]*" | cut -d "-" -f 2)
      patch_version=$(git describe --tags --abbrev=0 | grep -Eo "[0-9]*-[0-9]*-[0-9]*" | cut -d "-" -f 3)
      if [ $(( 10#$minor_version % 2 )) -eq 0 ] && [ $(( 10#$patch_version % 2 )) -eq 0 ]
      then
        craftctl set grade=stable
        craftctl set version="$(git describe --tags --abbrev=0)"
      else
        craftctl set grade=devel
        craftctl set version="$(git rev-parse --short HEAD).$(date -u +%d-%m-%y)"
      fi
      patch -i $CRAFT_PROJECT_DIR/snap/local/patches/ROOT/ACliC.patch -p 1
      patch -i $CRAFT_PROJECT_DIR/snap/local/patches/ROOT/cli_tools_pyenv_fix.patch -p 1
    override-build: |
      craftctl default

      # Correct CMake containing references to the build environment
      for file in $(grep "/root/parts/root/install\|/root/parts/root/build\|/root/stage" ${CRAFT_PART_INSTALL}/usr/local/cmake -r -I | cut -d ":" -f 1 | uniq); do
        sed -i 's!/root/parts/root/install!/snap/root-framework/current!g' $file
        sed -i 's!/root/parts/root/build!/snap/root-framework/current!g' $file
        sed -i 's!/root/stage!/snap/root-framework/current!g' $file
      done

      # Prevent use of -isystem in CMake configuration because it breaks "#include_next"
      for file in $(grep "isystem" ${CRAFT_PART_INSTALL}/usr/local/cmake -r -I | cut -d ":" -f 1 | uniq); do
        sed -i 's!\-isystem!\-I!g' $file
      done
    override-prime: |
      craftctl default
      cd $CRAFT_PRIME/usr/bin
      if [[ ! -f c++ ]] ; then ln -s g++ c++ ; fi # ACLiC
      if [[ ! -f cc ]] ; then ln -s gcc cc ; fi # E.G MadGraph
    after:
      [python-modules]


  extras:
    plugin: dump
    source: extras/

  python-modules:
    plugin: python
    source: extras/ # Defined above, will effectively no-op as it should deduplicate with extras part
    python-packages:
      - absl-py==2.0.0
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - Babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - fqdn==1.5.1
      - gast==0.5.4
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==3.10.0
      - idna==3.4
      - ipykernel==6.26.0
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - Jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.8.0
      - jupyter-lsp==2.2.0
      - jupyter_client==8.5.0
      - jupyter_core==5.4.0
      - jupyter_server==2.9.1
      - jupyter_server_terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.9
      - jupyterlab_server==2.25.0
      - keras==2.14.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - llvmlite==0.41.1
      - Markdown==3.5
      - MarkupSafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - metakernel==0.30.1
      - mistune==3.0.2
      - ml-dtypes==0.2.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - notebook==7.0.6
      - notebook_shim==0.2.3
      - numba==0.58.1
      - numpy==1.26.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - Pillow==10.1.0
      - platformdirs==3.11.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.4
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - Pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - PyYAML==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - QtPy==2.4.1
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.6
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - Send2Trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.3.3
      - traitlets==5.12.0
      - types-python-dateutil==2.8.19.14
      - typing_extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.7
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - Werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.14.1
    stage-packages:
      - libgomp1
      - libtbb2
    override-build: |
      craftctl default
      patch -d $CRAFT_PART_INSTALL -i $CRAFT_PROJECT_DIR/snap/local/patches/notebook/checkpoints.patch -p1
      patch -d $CRAFT_PART_INSTALL -i $CRAFT_PROJECT_DIR/snap/local/patches/notebook/atomic_saves.patch -p1
      patch -d $CRAFT_PART_INSTALL -i $CRAFT_PROJECT_DIR/snap/local/patches/notebook/disable_file_redirect.patch -p1

layout:
  /usr/include:
    bind: $SNAP/usr/include
  /usr/share/matplotlib:
    symlink: $SNAP/usr/share/matplotlib
  /usr/lib/x86_64-linux-gnu/libc_nonshared.a: # ACLiC
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libc_nonshared.a

plugs:
  home:
  network:
  opengl:
  x11:
  desktop:
  desktop-legacy:
  removable-media:
  shared-memory:
    private: true

apps:
  root-framework:
    command: usr/local/bin/root
    command-chain:
      - bin/setup-sandbox.sh
  pyroot:
    command: bin/pyroot.sh
    command-chain:
      - bin/setup-sandbox.sh
  genreflex:
    command: usr/local/bin/genreflex
    command-chain:
      - bin/setup-sandbox.sh
  hadd:
    command: usr/local/bin/hadd
    command-chain:
      - bin/setup-sandbox.sh
  hist2workspace:
    command: usr/local/bin/hist2workspace
    command-chain:
      - bin/setup-sandbox.sh
  prepareHistFactory:
    command: usr/local/bin/prepareHistFactory
    command-chain:
      - bin/setup-sandbox.sh
  proofserv:
    command: usr/local/bin/proofserv
    command-chain:
      - bin/setup-sandbox.sh
  rmkdepend:
    command: usr/local/bin/rmkdepend
    command-chain:
      - bin/setup-sandbox.sh
  root-config:
    command: usr/local/bin/root-config
    command-chain:
      - bin/setup-sandbox.sh
  rootbrowse:
    command: usr/local/bin/rootbrowse
    command-chain:
      - bin/setup-sandbox.sh
  rootcint:
    command: usr/local/bin/rootcint
    command-chain:
      - bin/setup-sandbox.sh
  rootcling:
    command: usr/local/bin/rootcling
    command-chain:
      - bin/setup-sandbox.sh
  rootcp:
    command: usr/local/bin/rootcp
    command-chain:
      - bin/setup-sandbox.sh
  rootdrawtree:
    command: usr/local/bin/rootdrawtree
    command-chain:
      - bin/setup-sandbox.sh
  rooteventselector:
    command: usr/local/bin/rooteventselector
    command-chain:
      - bin/setup-sandbox.sh
  rootls:
    command: usr/local/bin/rootls
    command-chain:
      - bin/setup-sandbox.sh
  rootmkdir:
    command: usr/local/bin/rootmkdir
    command-chain:
      - bin/setup-sandbox.sh
  rootmv:
    command: usr/local/bin/rootmv
    command-chain:
      - bin/setup-sandbox.sh
  rootprint:
    command: usr/local/bin/rootprint
    command-chain:
      - bin/setup-sandbox.sh
  rootrm:
    command: usr/local/bin/rootrm
    command-chain:
      - bin/setup-sandbox.sh
  roots:
    command: usr/local/bin/roots
    command-chain:
      - bin/setup-sandbox.sh
  rootslimtree:
    command: usr/local/bin/rootslimtree
    command-chain:
      - bin/setup-sandbox.sh
  rootreadspeed:
    command: usr/local/bin/rootreadspeed
    command-chain:
      - bin/setup-sandbox.sh
  xpdtest:
    command: usr/local/bin/xpdtest
    command-chain:
      - bin/setup-sandbox.sh
  root-exe:
    command: usr/local/bin/root.exe
    command-chain:
      - bin/setup-sandbox.sh
  rootn-exe:
    command: usr/local/bin/rootn.exe
    command-chain:
      - bin/setup-sandbox.sh
  rootnb-exe:
    command: usr/local/bin/rootnb.exe
    command-chain:
      - bin/setup-sandbox.sh
  roots-exe:
    command: usr/local/bin/roots.exe
    command-chain:
      - bin/setup-sandbox.sh
  proofserv-exe:
    command: usr/local/bin/proofserv.exe
    command-chain:
      - bin/setup-sandbox.sh
  cmake:
    command: usr/bin/cmake
    command-chain:
      - bin/setup-sandbox.sh
  make:
    command: usr/bin/make
    command-chain:
      - bin/setup-sandbox.sh
  run:
    command: bin/run.sh
    command-chain:
      - bin/setup-sandbox.sh
  pip:
    command: bin/pip
    command-chain:
      - bin/setup-sandbox.sh
