name: root-framework
base: core20
version: 'v6-22-02'
summary: Analyzing petabytes of data, scientifically.
description: |
  An open-source data analysis framework used by high energy physics and others. 
  
  This snap is intended to provide an easy to install package of the ROOT framework for the home user. It is provided for those who may find it useful, but users are reminded that there is a preference for the official ROOT upstream builds for professional use cases.
  
  Due to the sandboxing imposed by snapd, ROOT will only be able to read/write files in a users $HOME directory or over specific network protocols (E.G, preventing GVFS/Samba/etc). It is folly to attempt to read/write userdata in any other location using this package.
  
  This package can be invoked by running 'root-framework' into the terminal, and PyROOT as 'root-framework.pyroot'. Remember to import ROOT!

  Jupyter functionally is functional and can be accessed with 'root-framework --notebook'. JupyROOT may be preferential to running a Python interactive shell directly.
  
  This package is bundled with Python 3.8, and the Matplotlib, SciPy, NumPy, and Pandas libraries preconfigured. As it is a snap, it will not access nor depend on any other system libraries, including Jupyter itself.
  
  Users can view available ROOT binaries with 'snap info root-framework'. ROOT binaries are namespaced, so that hadd would be accessible as 'root-framework.hadd'

  Users are encouraged to make use of aliases to rename the binaries to their traditional values, if desired. For example, 'sudo snap alias root-framework root' would allow you to simply run 'root --notebook', similarly, 'sudo snap alias root-framework.hadd hadd', etc.

grade: stable
confinement: strict
license: LGPL-2.1+
architectures:
  - build-on: amd64

parts:
  root:
    plugin: cmake
    source: https://github.com/root-project/root.git
    source-tag: v6-22-02 
    source-depth: 1
    build-packages:
      - libx11-dev
      - libxpm-dev
      - libxft-dev
      - libxext-dev
      - libpython3-dev
      - libssl-dev
      - libpcre++-dev
      - liblzma-dev
      - libzstd-dev
      - libxxhash-dev
      - liblz4-dev
      - libgif-dev
      - libtiff-dev
      - libjpeg-dev
      - libafterimage-dev
      - libgsl-dev
      - xlibmesa-glu-dev
      - libxml2-dev
      - libsqlite3-dev
      - libfftw3-dev
      - libcfitsio-dev
      - libtbb-dev
      - libblas-dev
      - libftgl-dev
      - libpythia8-dev
      - python3-numpy
      - libglew-dev
      - davix-dev
      - libgl2ps-dev
    stage-packages:
      - libafterimage0
      - libasn1-8-heimdal
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcfitsio8
      - libcurl3-gnutls
      - libdatrie1
      - libfftw3-double3
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libftgl2
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgsl23
      - libgslcblas0
      - libgssapi3-heimdal
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu66
      - libjbig0
      - libjpeg-turbo8
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libpython3.8
      - libroken18-heimdal
      - librsvg2-2
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libtbb2
      - libthai0
      - libtiff5
      - libwebp6
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxml2
      - libxpm4
      - libxrender1
      - libxxhash0
      - libblas3
      - libstdc++-9-dev
      - libc6-dev
      - libdavix0v5
      - libgl2ps1.4
      - libglew2.1
      - libpythia8v5
      - jupyter
      - jupyter-notebook
      - python3-scipy
      - python3-numpy
      - python3-matplotlib
      - python3-pandas
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
      

  extras:
    plugin: dump
    source: extras/

environment:
  PYTHONPATH: ${SNAP}/usr/local/lib:${SNAP}/usr/lib/python3/dist-packages
  LD_LIBRARY_PATH: ${SNAP}/usr/local/lib:${LD_LIBRARY_PATH}
  DISABLE_WAYLAND: 1
  MATPLOTLIBRC: ${SNAP}/etc/matplotlibrc

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/include:
    bind: $SNAP/usr/include
  /usr/share/matplotlib:
    bind: $SNAP/usr/share/matplotlib

apps:
  root-framework:
    command: usr/local/bin/root
    command-chain: 
      - bin/setup-sandbox.sh
    plugs:
      - home
      - network
      - opengl
      - x11
      - desktop
      - desktop-legacy
  pyroot:
    command: bin/pyroot.sh
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  genreflex:
    command: usr/local/bin/genreflex
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  hadd:
    command: usr/local/bin/hadd
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  hist2workspace:
    command: usr/local/bin/hist2workspace
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  memprobe:
    command: usr/local/bin/memprobe
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  prepareHistFactory:
    command: usr/local/bin/prepareHistFactory
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  proofserv:
    command: usr/local/bin/proofserv
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rmkdepend:
    command: usr/local/bin/rmkdepend
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  root-config:
    command: usr/local/bin/root-config
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootbrowse:
    command: usr/local/bin/rootbrowse
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootcint:
    command: usr/local/bin/rootcint
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootcling:
    command: usr/local/bin/rootcling
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootcp:
    command: usr/local/bin/rootcp
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootdrawtree:
    command: usr/local/bin/rootdrawtree
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rooteventselector:
    command: usr/local/bin/rooteventselector
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootls:
    command: usr/local/bin/rootls
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootmkdir:
    command: usr/local/bin/rootmkdir
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootmv:
    command: usr/local/bin/rootmv
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootprint:
    command: usr/local/bin/rootprint
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootrm:
    command: usr/local/bin/rootrm
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  roots:
    command: usr/local/bin/roots
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  rootslimtree:
    command: usr/local/bin/rootslimtree
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
  xpdtest:
    command: usr/local/bin/xpdtest
    command-chain: 
     - bin/setup-sandbox.sh
    plugs:
     - home
     - network
     - opengl
     - x11
     - desktop
     - desktop-legacy
