name: Nightly builds
on:
  schedule:
   - cron: "0 20 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v3
      with:
        name: 'root-framework-nightly.snap'
        path: ${{ steps.build.outputs.snap}}
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: latest/edge

